on: [push]

jobs:
  # unit_tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: npm ci
  #   - run: npm test

  test_action_job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2

      - id: speedcurve_deploy
        uses: ./
        with:
          api_key: ${{ secrets.SPEEDCURVE_API_KEY }}
          site_id: 335016

      - run: echo "The SpeedCurve deploy ID is ${{ steps.speedcurve_deploy.outputs.deploy_id }}"
